### ISSUE TITLE
Ability to choose between local and session storage

### ISSUE THREAD

**Issue by chrissainty** [Blazored/AutoSaveEditForm#2]
We don't currently allow the developer to choose where to store the saved form model, it's hardcoded to local storage. 

This should be configurable by the developer via a parameter on the `BlazoredAutoSaveEditForm` component.

```csharp
[Parameter] public StorageTypes StorageType { get; set; }

public enum StorageTypes
{
    LocalStorage,
    SessionStorage
}
```

**Comment by ThaRaven403** [comment]
Hey Chris, just wanted to confirm this is not already being worked on, I'd like to grab it!

**Comment by chrissainty** [comment]
Hey @ThaRaven403, yes, it's still available and it's all yours! :) Thanks for the help.

**Comment by ThaRaven403** [comment]
Glad to help! If you're in need of some help, feel free to let me know!
